### PR TITLE
Added packages needed by oab-java

### PR DESCRIPTION
**Pull request by jeremyharris**
I ran into a problem where the AMI ended up being bad because java was never built. The error is here: https://gist.github.com/jeremyharris/0fe6d53c108028ed8f66#file-gistfile1-txt-L57

I tried to inspect the oab-java log while puppet was installing it but for some reason it never generated a log. Then I booted up the bad AMI, ran `oab-java.sh` manually and dealt with the errors one at a time. It turned out it wouldn't install because it was missing certain packages here and there, which I added.

After adding these packages and running it again, the AMI built correctly and ran successfully using Minecloud.

P.S. Thanks for this project - it saved me a ton of time and effort and turned out better than what I was probably going to end up with :)

### CODE REVIEW

**Comment by toffer** [comment]
@jeremyharris Thanks for this update. I'll test it out later tonight.

Another approach I'm considering is switching from running the oab-java script, and instead using the webupd8 PPA repository: https://launchpad.net/~webupd8team/+archive/java.

I didn't know about this PPA repository when I first built Minecloud, but I've seen other projects use it, and it seems like it's got a pretty good reputation for reliability. What are your thoughts? Any experience with it?

Anyway, I'll most likely merge your changes and consider using the webupd8 PPA at a later time.

**Comment by toffer** [comment]
More details: These dependencies used to be installed automatically in the oab-java.sh script, but for some reason, that step was removed 2 days ago.

I filed an issue here: https://github.com/flexiondotorg/oab-java6/issues/122

**Comment by jeremyharris** [comment]
I honestly don't know anything about either of these repos. Interesting that it was removed 2 days ago, guess I joined in the fun just in time ;)

**Comment by toffer** [comment]
@jeremyharris It should be all good now.

P.S. Thanks for the kind words about the project!

**Pull request merged**
